// -*- coding: utf-8, tab-width: 2 -*-

import bob from '../../util/bundledOptionalBundles';

export default bob('software_debPkg', {
  basicImageEditing: true,
  configMgmt: true,
  dataRecovery: true,
  debPkgLists_ubuntuDefault: true,
  debPkgUtil: true,
  debugUtil: true,
  develBasics: true,
  dialogScripting: true,
  diskPartMgmt: true,
  diskSmart: true,
  fileEncodings: true,
  fileSystems: true,
  fileViewers: true,
  grub: true,
  hexEditors: true,
  iconsGnomeDefault: true,
  kernel: true,
  math: true,
  networkBasics: true,
  networkDataTransfer: true,
  networkDebug: true,
  nodejs: true,
  openbox: true,
  remoteDesktop: true,
  remoteShell: true,
  rtfm: true,
  shell: true,
  sysCore: true,
  sysInstall: true,
  terminalEmus: true,
  textEditors: true,
  vcs: true,
  xorgBasics: true,
  xorgClipboardPersist: true,
});
