%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

name: '☂ CI tests'

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  job_npm_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        t:
          - { node: 24, eslint: 8 }

    steps:
      - uses: actions/checkout@v6

      - name: 'Install ghciu'
        uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental
        with:
          nodejs_version: '${{ matrix.t.node }}'

      - name: 'Use the experimental version of ubborg-planner-pmb'
        run: >
          ghciu npm install --save "${{ github.repository_owner
            }}/ubborg-planner-pmb-js#experimental"

      - run: 'ghciu npm install "eslint@${{ matrix.t.eslint }}"'
      - run: ghciu npm install .
      - name: 'Symlink repo as module'
        run: >
          ln --symbolic --no-target-directory
          -- .. node_modules/ubborg-usecase-rescuedisk-pmb
      - run: ghciu npm test

      - run: 'ghciu ./test/ci_log_hints.sh'
        if: '!cancelled()'

      - name: 'Pack the ghciu logs as an artifact.'
        if: '!cancelled()'
        uses: actions/upload-artifact@v6
        with:
          name: 'ghciu_logs.${{ env.GHCIU_TRACE_JOB }}'
          path: .ghciu/logs.local/




...
